# Generated by Django 6.0 on 2026-03-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('artist', models.CharField(db_index=True, max_length=255)),
                ('album', models.CharField(db_index=True, max_length=255)),
                ('file_path', models.CharField(help_text='Percorso relativo per file locali o ID per Google Drive', max_length=1024, unique=True)),
                ('cover_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('source', models.CharField(choices=[('local', 'Local File'), ('gdrive', 'Google Drive')], default='local', max_length=20)),
                ('drive_file_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['artist', 'album', 'title'],
            },
        ),
    ]
