# Generated by Django 6.0 on 2026-03-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='folder_path',
            field=models.CharField(blank=True, db_index=True, help_text='Percorso logico della cartella (es. Artista/Album o ID genitore)', max_length=2048, null=True),
        ),
    ]
